### ISSUE TITLE
System gets panic  while uninstalling the filter driver.

### ISSUE THREAD

**Issue by expoinfy** [slavaim/MacOSX-FileSystem-Filter#1]
Hi,
When I am uninstalling  the kext , system gets panic.

**Comment by slavaim** [comment]
I need a panic log reported by the system ( this is not a dump file ) that contains a call stack and type of error. Normally panic logs can be found in /Library/Logs/DiagnosticReports

**Comment by expoinfy** [comment]
Anonymous UUID:       EEA0ECFD-456A-4BCA-7DC9-803E6BD56AC

Thu May  5 11:42:43 2016

**\* Panic Report ***
panic(cpu 0 caller 0xffffff8023d69a15): "vm_map_delete(0xffffff8027678d88,0xffffff812dc85000,0xffffff812e028000): " "hole after 0xffffff8031a91300 at 0xffffff803dce3000\n"@/Library/Caches/com.apple.xbs/Sources/xnu/xnu-3247.1.106/osfmk/vm/vm_map.c:7270
Backtrace (CPU 0), Frame : Return Address
0xffffff90f651af90 : 0xffffff8023ce5355 
0xffffff90f651b010 : 0xffffff8023d69a14 
0xffffff90f651b120 : 0xffffff8023d5f0a3 
0xffffff90f651b150 : 0xffffff8023d5a572 
0xffffff90f651b180 : 0xffffff8023ceecb1 
0xffffff90f651b1a0 : 0xffffff8024280831 
0xffffff90f651b1c0 : 0xffffff7fa4622a33 
0xffffff90f651b3f0 : 0xffffff7fa4451b0a 
0xffffff90f651b440 : 0xffffff7fa44542c1 
0xffffff90f651b4a0 : 0xffffff7fa4459d22 
0xffffff90f651b570 : 0xffffff7fa5e210e1 
0xffffff90f651b6e0 : 0xffffff8023f404b5 
0xffffff90f651b740 : 0xffffff8023ee6216 
0xffffff90f651b890 : 0xffffff7fa49cfdd3 
0xffffff90f651b8d0 : 0xffffff8023ef30b2 
0xffffff90f651ba60 : 0xffffff8023eef23d 
0xffffff90f651bca0 : 0xffffff8023eee8b4 
0xffffff90f651bcd0 : 0xffffff7fa49cdfbe 
0xffffff90f651bd60 : 0xffffff8023f2dd94 
0xffffff90f651bde0 : 0xffffff8023f22b5a 
0xffffff90f651be60 : 0xffffff80241ca284 
0xffffff90f651bf00 : 0xffffff80241ca4d1 
0xffffff90f651bf60 : 0xffffff802422ace2 
0xffffff90f651bfb0 : 0xffffff8023df4895 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOStorageFamily(2.1)[956BA33B-5C0A-37E9-B395-538D1BD95AC0]@0xffffff7fa444d000->0xffffff7fa4473fff
         com.apple.BootCache(37.0)[AD81CD1C-5A58-34E2-4595-EA182565C831]@0xffffff7fa5e1d000->0xffffff7fa5e26fff
         com.mytest.devicehook(1.0)[7048A329-36E5-3E86-84E9-C58BFD484B02]@0xffffff7fa4620000->0xffffff7fa4626fff
            dependency: com.mytest.driver(1.0.0)[4ABF50De-C101-33AD-BED1-1C2E87EB7567]@0xffffff7fa4607000
            dependency: com.apple.iokit.IOStorageFamily(2)[936BA336-5C0A-37E9-B395-538D1BD95AC0]@0xffffff7fa444d000
         com.apple.filesystems.msdosfs(1.10)[D4BCC813-35FF-3FB3-8EAC-EF0C93633EB0]@0xffffff7fa49c4000->0xffffff7fa49d2fff

BSD process name corresponding to current thread: DesktopServicesH
Boot args: debug=0x146 kext-dev-mode=1

Mac OS version:
15A271

Kernel version:
Darwin Kernel Version 15.0.0: Aug 23 16:41:34 PDT 2015; root:xnu-3247.1.106~5/RELEASE_X86_64
Kernel UUID: 2B58E1F7-2900-3A21-8405-6F9719086009
Kernel slide:     0x0000000013a00000
Kernel text base: 0xffffff8013c00000
__HIB  text base: 0xffffff8023b00000

**Comment by slavaim** [comment]
Can you get a call stack by connecting a debugger? You need to load symbols for com.mytest.\* drivers as I believe these are your drivers.

**Comment by expoinfy** [comment]
Hi, 

I have removed all the 3rd party drivers, and it's a fresh osx yosemite image. I installed your kext, but when did kextunload system gets panic. Below is the latest panic report.

Anonymous UUID:       AB768AC5-5C0A-F7C1-5794-BB6DCF74A18B

Sun May  8 18:57:30 2016

**\* Panic Report ***
panic(cpu 2 caller 0xffffff8003616df2): Kernel trap at 0xffffff7f85def0ff, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x0000000000000000, CR3: 0x00000001e3bfe072, CR4: 0x00000000000626e0
RAX: 0x0000000000000000, RBX: 0x00000000000001b4, RCX: 0x0000000000000000, RDX: 0xffffff80d4d9bb30
RSP: 0xffffff80d4d9bb10, RBP: 0xffffff80d4d9bb50, RSI: 0xffffff80d4d9bb30, RDI: 0xffffff80175d9180
R8:  0x0000000000000000, R9:  0xffffff8013207dc0, R10: 0x0000000000000000, R11: 0x0000000000000000
R12: 0xffffff801178e380, R13: 0xffffff80118d8bc0, R14: 0xffffff8003d12cb0, R15: 0xffffff8019bbaa00
RFL: 0x0000000000010207, RIP: 0xffffff7f85def0ff, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0x2

Backtrace (CPU 2), Frame : Return Address
0xffffff80d4d9b7c0 : 0xffffff800352ad21 
0xffffff80d4d9b840 : 0xffffff8003616df2 
0xffffff80d4d9ba00 : 0xffffff8003633ca3 
0xffffff80d4d9ba20 : 0xffffff7f85def0ff 
0xffffff80d4d9bb50 : 0xffffff7f85def03b 
0xffffff80d4d9bb70 : 0xffffff7f85df1172 
0xffffff80d4d9bba0 : 0xffffff8003a75af3 
0xffffff80d4d9bbd0 : 0xffffff8003a75936 
0xffffff80d4d9bbf0 : 0xffffff8003aaa2af 
0xffffff80d4d9bc10 : 0xffffff8003acf4dc 
0xffffff80d4d9bc40 : 0xffffff8003acf705 
0xffffff80d4d9bc80 : 0xffffff8003a67f3f 
0xffffff80d4d9bcc0 : 0xffffff8003a6f437 
0xffffff80d4d9bd40 : 0xffffff8003a80c56 
0xffffff80d4d9bdc0 : 0xffffff800357230d 
0xffffff80d4d9be10 : 0xffffff800352ef8c 
0xffffff80d4d9be40 : 0xffffff80035139f3 
0xffffff80d4d9be90 : 0xffffff800352429d 
0xffffff80d4d9bf10 : 0xffffff800360231a 
0xffffff80d4d9bfb0 : 0xffffff80036344c6 
      Kernel Extensions in backtrace:
         com.SlavaImameev.FsdFilter(1.0)[9F23D518-D227-3B63-A38F-D3E4821CDE00]@0xffffff7f85ded000->0xffffff7f85df3fff

BSD process name corresponding to current thread: kextunload
Boot args: debug=0x146 kext-dev-mode=1

Mac OS version:
14F1605

Kernel version:
Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64
Kernel UUID: 06D286E3-A8A1-3BE7-A7EB-EAC6E0C69758
Kernel slide:     0x0000000003200000
Kernel text base: 0xffffff8003400000
__HIB  text base: 0xffffff8003300000
System model name: Macmini5,1 (Mac-8ED6AF5B48C039E1)

System uptime in nanoseconds: 379809497555
last loaded kext at 320702206061: com.apple.iokit.SCSITaskUserClient    3.7.5 (addr 0xffffff7f85df4000, size 36864)
last unloaded kext at 268556874208: com.apple.driver.AppleUSBCDC    4.3.3b1 (addr 0xffffff7f85d52000, size 16384)
loaded kexts:
com.SlavaImameev.FsdFilter  1
com.apple.iokit.SCSITaskUserClient  3.7.5
com.apple.driver.AppleUSBCDC    4.3.3b1
com.apple.filesystems.smbfs 3.0.2
com.apple.filesystems.msdosfs   1.10
com.apple.driver.AppleHWSensor  1.9.5d0
com.apple.driver.AudioAUUC  1.70
com.apple.driver.ApplePlatformEnabler   2.2.0d4
com.apple.driver.AGPM   110.19.6
com.apple.filesystems.autofs    3.0
com.apple.iokit.IOBluetoothSerialManager    4.3.6f3
com.apple.driver.AppleOSXWatchdog   1
com.apple.driver.AppleMikeyHIDDriver    124
com.apple.driver.AppleHDA   272.18.3
com.apple.driver.AppleUpstreamUserClient    3.6.1
com.apple.driver.AppleMCCSControl   1.2.12
com.apple.iokit.IOUserEthernet  1.0.1
com.apple.Dont_Steal_Mac_OS_X   7.0.0
com.apple.driver.AppleHWAccess  1
com.apple.driver.AppleIntelHD3000Graphics   10.0.0
com.apple.driver.AppleMikeyDriver   272.18.3
com.apple.driver.AppleHV    1
com.apple.driver.ACPI_SMC_PlatformPlugin    1.0.0
com.apple.driver.AppleIntelSlowAdaptiveClocking 4.0.0
com.apple.driver.AppleThunderboltIP 2.0.2
com.apple.driver.AppleLPC   1.7.3
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport 4.3.6f3
com.apple.driver.AppleSMCPDRC   1.0.0
com.apple.driver.AppleIntelSNBGraphicsFB    10.0.0
com.apple.driver.AppleIRController  327.5
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless 1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib 1.0.0
com.apple.BootCache 36
com.apple.driver.XsanFilter 404
com.apple.iokit.IOAHCIBlockStorage  2.7.1
com.apple.driver.AppleUSBHub    705.4.2
com.apple.iokit.AppleBCM5701Ethernet    10.1.3
com.apple.driver.AppleFWOHCI    5.5.2
com.apple.driver.AppleSDXC  1.6.5
com.apple.driver.AirPort.Brcm4331   800.20.24
com.apple.driver.AppleAHCIPort  3.1.2
com.apple.driver.AppleUSBEHCI   705.4.14
com.apple.driver.AppleRTC   2.0
com.apple.driver.AppleACPIButtons   3.1
com.apple.driver.AppleHPET  1.8
com.apple.driver.AppleSMBIOS    2.1
com.apple.driver.Apple

**Comment by slavaim** [comment]
I overlooked that you were talking about unload as you didn't provide me with a call stack. In current version driver unload is not supported, you need to disable driver unload. You can add unload support by unhooking all hooked file system drivers. Practically unload for a hooking file system filter driver is a dangerous operation as it is hard to implement it correctly to avoid race conditions and preserve data consistency.  To process unload correctly you need to process the following cases
-  driver code being in any call stack, unloading a driver results in a panic as control returns to unloaded code
- driver code being called, i.e. any processors IP register points to any function in a driver
- any data changed by a driver should not crash the system or damage user or system data, for example if the driver implements any data modification it should guarantee data consistency on unload  

The only feasible way to implement this is dividing a driver in two parts - one part can be unloaded and another part is never unloaded.  Unloading complicates the code as you have to synchronize the code with unloading procedure, this increases complexity and as a result of this complexity and nondeterminism in the system state it's never implemented correctly

**Comment by slavaim** [comment]
I fixed the crash and made the module unloadable.
